# Generated by Django 5.1.4 on 2024-12-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitals', '0003_myexamplemodelforexcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyExampleModelForExcel',
        ),
    ]
